name: Run lint and tests

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: pipx install ruff

      - name: Lint code with Ruff
        run: ruff check --fix --output-format=github

      - name: Check formatting with Ruff
        run: ruff format
        continue-on-error: true

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install package
        run: pip install -e .

      - name: Run tests
        run: pytest